/*
 * This file is generated by jOOQ.
*/
package swust.xl.pojo.po.mysql.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article implements Serializable {

    private static final long serialVersionUID = 1301731801;

    private Long   aid;
    private String type;
    private String title;
    private String content;
    private String picturepath;

    public Article() {}

    public Article(Article value) {
        this.aid = value.aid;
        this.type = value.type;
        this.title = value.title;
        this.content = value.content;
        this.picturepath = value.picturepath;
    }

    public Article(
        Long   aid,
        String type,
        String title,
        String content,
        String picturepath
    ) {
        this.aid = aid;
        this.type = type;
        this.title = title;
        this.content = content;
        this.picturepath = picturepath;
    }

    public Long getAid() {
        return this.aid;
    }

    public void setAid(Long aid) {
        this.aid = aid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getPicturepath() {
        return this.picturepath;
    }

    public void setPicturepath(String picturepath) {
        this.picturepath = picturepath;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Article (");

        sb.append(aid);
        sb.append(", ").append(type);
        sb.append(", ").append(title);
        sb.append(", ").append(content);
        sb.append(", ").append(picturepath);

        sb.append(")");
        return sb.toString();
    }
}
