/*
 * This file is generated by jOOQ.
*/
package cn.signit.pojo.po.mysql;


import cn.signit.pojo.po.mysql.tables.UserPerson;
import cn.signit.pojo.po.mysql.tables.VerifyStatistics;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.user_person</code>.
     */
    public static final UserPerson USER_PERSON = cn.signit.pojo.po.mysql.tables.UserPerson.USER_PERSON;

    /**
     * The table <code>test.verify_statistics</code>.
     */
    public static final VerifyStatistics VERIFY_STATISTICS = cn.signit.pojo.po.mysql.tables.VerifyStatistics.VERIFY_STATISTICS;
}
