/*
 * This file is generated by jOOQ.
*/
package swust.xl.pojo.po.mysql.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import swust.xl.pojo.po.mysql.tables.UserPerson;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPersonRecord extends UpdatableRecordImpl<UserPersonRecord> implements Record9<Long, String, String, String, Byte, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1451517471;

    /**
     * Setter for <code>test.user_person.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.user_person.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>test.user_person.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.user_person.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.user_person.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.user_person.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.user_person.sex</code>.
     */
    public void setSex(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.user_person.sex</code>.
     */
    public String getSex() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.user_person.is_system</code>.
     */
    public void setIsSystem(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.user_person.is_system</code>.
     */
    public Byte getIsSystem() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>test.user_person.salt</code>.
     */
    public void setSalt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.user_person.salt</code>.
     */
    public String getSalt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.user_person.password_salt</code>.
     */
    public void setPasswordSalt(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.user_person.password_salt</code>.
     */
    public String getPasswordSalt() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test.user_person.regist_datetime</code>.
     */
    public void setRegistDatetime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.user_person.regist_datetime</code>.
     */
    public Timestamp getRegistDatetime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>test.user_person.last_login_datetime</code>.
     */
    public void setLastLoginDatetime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.user_person.last_login_datetime</code>.
     */
    public Timestamp getLastLoginDatetime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Byte, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, Byte, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserPerson.USER_PERSON.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserPerson.USER_PERSON.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserPerson.USER_PERSON.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserPerson.USER_PERSON.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return UserPerson.USER_PERSON.IS_SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserPerson.USER_PERSON.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserPerson.USER_PERSON.PASSWORD_SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return UserPerson.USER_PERSON.REGIST_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return UserPerson.USER_PERSON.LAST_LOGIN_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsSystem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getPasswordSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getRegistDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getLastLoginDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsSystem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getPasswordSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getRegistDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getLastLoginDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value4(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value5(Byte value) {
        setIsSystem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value6(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value7(String value) {
        setPasswordSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value8(Timestamp value) {
        setRegistDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord value9(Timestamp value) {
        setLastLoginDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserPersonRecord values(Long value1, String value2, String value3, String value4, Byte value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPersonRecord
     */
    public UserPersonRecord() {
        super(UserPerson.USER_PERSON);
    }

    /**
     * Create a detached, initialised UserPersonRecord
     */
    public UserPersonRecord(Long id, String username, String email, String sex, Byte isSystem, String salt, String passwordSalt, Timestamp registDatetime, Timestamp lastLoginDatetime) {
        super(UserPerson.USER_PERSON);

        set(0, id);
        set(1, username);
        set(2, email);
        set(3, sex);
        set(4, isSystem);
        set(5, salt);
        set(6, passwordSalt);
        set(7, registDatetime);
        set(8, lastLoginDatetime);
    }
}
