/*
 * This file is generated by jOOQ.
*/
package swust.xl.pojo.po.mysql;


import javax.annotation.Generated;

import swust.xl.pojo.po.mysql.tables.Article;
import swust.xl.pojo.po.mysql.tables.Comments;
import swust.xl.pojo.po.mysql.tables.Users;


/**
 * Convenience access to all tables in user
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user.article</code>.
     */
    public static final Article ARTICLE = swust.xl.pojo.po.mysql.tables.Article.ARTICLE;

    /**
     * The table <code>user.comments</code>.
     */
    public static final Comments COMMENTS = swust.xl.pojo.po.mysql.tables.Comments.COMMENTS;

    /**
     * The table <code>user.users</code>.
     */
    public static final Users USERS = swust.xl.pojo.po.mysql.tables.Users.USERS;
}
