/*
 * This file is generated by jOOQ.
*/
package swust.xl.pojo.po.mysql;


import javax.annotation.Generated;

import swust.xl.pojo.po.mysql.tables.UserPerson;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.user_person</code>.
     */
    public static final UserPerson USER_PERSON = swust.xl.pojo.po.mysql.tables.UserPerson.USER_PERSON;
}
